import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

STATE_FILE = ROOT / "state.json"
INCIDENTS_FILE = ROOT / "incidents.json"
INCIDENTS_MD = ROOT / "INCIDENTS.md"
POSTMORTEMS_DIR = ROOT / "incidents"


def parse_time(value):
    if not value:
        return None

    return datetime.fromisoformat(value)


def format_timestamp(value):
    dt = parse_time(value)

    if not dt:
        return "—"

    return dt.astimezone(timezone.utc).strftime(
        "%Y-%m-%d %H:%M:%S UTC"
    )


def format_duration(seconds):
    if seconds is None:
        return "—"

    seconds = max(0, int(seconds))

    if seconds < 60:
        return f"{seconds}s"

    minutes = seconds // 60
    remaining_seconds = seconds % 60

    if minutes < 60:
        return f"{minutes}m {remaining_seconds}s"

    hours = minutes // 60
    remaining_minutes = minutes % 60

    return f"{hours}h {remaining_minutes}m"


def current_duration(incident):
    started = parse_time(incident.get("started_at"))

    if not started:
        return None

    now = datetime.now(timezone.utc)

    return int((now - started).total_seconds())


def nice_cause(cause):
    if not cause:
        return "Unknown"

    return cause.replace("_", " ").title()


def severity_for_cause(cause):
    severity_map = {
        "manual chaos": "SEV-2",
        "cpu saturation": "SEV-2",
        "memory leak": "SEV-2",
    }

    return severity_map.get(cause, "SEV-3")


# ---------------------------------------------------------
# LOAD DATA
# ---------------------------------------------------------

with open(STATE_FILE, encoding="utf-8") as f:
    state = json.load(f)

with open(INCIDENTS_FILE, encoding="utf-8") as f:
    incidents = json.load(f)


POSTMORTEMS_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ---------------------------------------------------------
# SUMMARY METRICS
# ---------------------------------------------------------

total_incidents = len(incidents)

resolved_incidents = [
    incident
    for incident in incidents
    if incident.get("resolved_at") is not None
]

active_incidents = [
    incident
    for incident in incidents
    if incident.get("resolved_at") is None
]

resolved_count = len(resolved_incidents)
active_count = len(active_incidents)

average_mttr = state.get("average_mttr_seconds")
last_mttr = state.get("last_mttr_seconds")


# ---------------------------------------------------------
# GENERATE INCIDENTS.MD
# ---------------------------------------------------------

lines = [
    "# 🚨 Incident History",
    "",
    "> Automatically generated by DevOps Tamagotchi.",
    "",
    "This file is generated from `incidents.json` by GitHub Actions.",
    "Do not edit it manually.",
    "",
    "## 📊 Reliability",
    "",
    "| Metric | Value |",
    "|---|---:|",
    f"| Total incidents | {total_incidents} |",
    f"| Resolved | {resolved_count} |",
    f"| Active | {active_count} |",
    f"| Average MTTR | {format_duration(average_mttr)} |",
    f"| Last MTTR | {format_duration(last_mttr)} |",
    "",
]


# ---------------------------------------------------------
# ACTIVE INCIDENT
# ---------------------------------------------------------

if active_incidents:
    incident = active_incidents[-1]

    duration = current_duration(incident)

    lines.extend(
        [
            "## 🔴 Active Incident",
            "",
            (
                f"### Incident #{incident['id']} — "
                f"{nice_cause(incident.get('cause'))}"
            ),
            "",
            "| Field | Value |",
            "|---|---|",
            "| Status | 🔴 ACTIVE |",
            f"| Cause | {nice_cause(incident.get('cause'))} |",
            (
                f"| Started | "
                f"{format_timestamp(incident.get('started_at'))} |"
            ),
            f"| Duration | {format_duration(duration)} |",
            "",
        ]
    )

else:
    lines.extend(
        [
            "## 🟢 Current Status",
            "",
            "There are no active tracked incidents.",
            "",
        ]
    )


# ---------------------------------------------------------
# INCIDENT LOG
# ---------------------------------------------------------

lines.extend(
    [
        "## 📜 Incident Log",
        "",
        "| # | Cause | Started | Resolved | MTTR | Status |",
        "|---:|---|---|---|---:|---|",
    ]
)


for incident in reversed(incidents):
    resolved = incident.get("resolved_at")

    if resolved:
        status = "🟢 Resolved"
        mttr = format_duration(
            incident.get("mttr_seconds")
        )
    else:
        status = "🔴 Active"
        mttr = "—"

    lines.append(
        "| "
        f"{incident['id']} | "
        f"{nice_cause(incident.get('cause'))} | "
        f"{format_timestamp(incident.get('started_at'))} | "
        f"{format_timestamp(resolved)} | "
        f"{mttr} | "
        f"{status} |"
    )


if not incidents:
    lines.append(
        "| — | No incidents yet | — | — | — | 🟢 Quiet |"
    )


# ---------------------------------------------------------
# POSTMORTEM LINKS
# ---------------------------------------------------------

lines.extend(
    [
        "",
        "## 📝 Postmortems",
        "",
    ]
)


for incident in reversed(resolved_incidents):
    incident_id = int(incident["id"])

    filename = f"incident-{incident_id:03d}.md"

    lines.append(
        f"- [Incident #{incident_id:03d}]"
        f"(./incidents/{filename})"
    )


if not resolved_incidents:
    lines.append(
        "No resolved incidents yet."
    )


lines.append("")


INCIDENTS_MD.write_text(
    "\n".join(lines),
    encoding="utf-8",
)


# ---------------------------------------------------------
# GENERATE POSTMORTEMS
# ---------------------------------------------------------

expected_postmortems = set()


for incident in resolved_incidents:
    incident_id = int(incident["id"])

    filename = f"incident-{incident_id:03d}.md"

    postmortem_file = POSTMORTEMS_DIR / filename

    expected_postmortems.add(postmortem_file)

    cause = nice_cause(
        incident.get("cause")
    )

    severity = severity_for_cause(
        incident.get("cause")
    )

    started = format_timestamp(
        incident.get("started_at")
    )

    resolved = format_timestamp(
        incident.get("resolved_at")
    )

    mttr = format_duration(
        incident.get("mttr_seconds")
    )

    content = f"""# 🚨 Incident #{incident_id:03d}

> Automatically generated DevOps Tamagotchi postmortem.

## Summary

Production experienced a simulated **{cause}** incident.

The incident was created by the DevOps Tamagotchi chaos workflow and remained active until the recovery workflow resolved it.

## Timeline

| Event | Time |
|---|---|
| 🔴 Incident started | {started} |
| 💚 Recovery completed | {resolved} |

## Metrics

| Metric | Value |
|---|---|
| Incident | #{incident_id:03d} |
| Severity | {severity} |
| Cause | {cause} |
| MTTR | {mttr} |
| Status | 🟢 Resolved |

## Root Cause

The simulated production environment entered an unhealthy state due to **{cause.lower()}**.

In other words: somebody intentionally poked production.

## Resolution

The incident was resolved using the DevOps Tamagotchi recovery workflow.

The workflow:

1. restored the Tamagotchi to a healthy state;
2. recorded the resolution timestamp;
3. calculated MTTR;
4. updated `incidents.json`;
5. regenerated the live dashboard;
6. regenerated the incident history and this postmortem.

## Follow-up

No actual production systems were harmed in the making of this incident.

The DevOps Tamagotchi has returned to:

**🟢 HEALTHY**
"""

    postmortem_file.write_text(
        content,
        encoding="utf-8",
    )


# ---------------------------------------------------------
# CLEAN UP STALE POSTMORTEMS
# ---------------------------------------------------------

for file in POSTMORTEMS_DIR.glob("incident-*.md"):
    if file not in expected_postmortems:
        file.unlink()


# ---------------------------------------------------------
# OUTPUT
# ---------------------------------------------------------

print(
    f"Generated INCIDENTS.md | "
    f"{total_incidents} total | "
    f"{resolved_count} resolved | "
    f"{active_count} active"
)

print(
    f"Generated {len(resolved_incidents)} postmortem(s)"
)